### ISSUE TITLE
TypeError: Cannot read property 'parsers' of undefined

### ISSUE THREAD

**Issue by jctaillandier** [pghalliday/socket.io-serialport#1]
Hey, running this with newest version, keep having the error returned. 
Here's my full code:
```
//import serial port js package
var serialport = require("serialport");
var SerialPort = serialport.SerialPort;
var portName = process.argv[2];

//opening a port
var myPort = new SerialPort(portName, {
  baudRate: 9600,
  parser: SerialPort.parsers.readline('\n')
});

myPort.on("open", onOpen);
myPort.on("data" , onData);

function onOpen(){
    console.log("Port open");
}

function onData(){
    console.log("data transfer completed.");
}
```
And the full error:

```
$ node serialComms.js COM3
C:\Users\小米笔记本\Documents\Arduino\dhtTempTest\serialComms.js:9
  parser: SerialPort.parsers.readline('\n')
                     ^

TypeError: Cannot read property 'parsers' of undefined
    at Object.<anonymous> (C:\Users\小米笔记本\Documents\Arduino\dhtTempTest\serialComms.js:9:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

```

I already had a look at : https://github.com/node-serialport/node-serialport/issues/937 but nothing could fix it for me.

**Comment by jctaillandier** [comment]
Changing parser value to 
`parser: SerialPort.parsers.raw`
Then gives me this error:
```

$ node serialComms.js COM3
C:\Users\小米笔记本\Documents\Arduino\dhtTempTest\serialComms.js:9
  parser: SerialPort.parsers.raw
                     ^

TypeError: Cannot read property 'parsers' of undefined
    at Object.<anonymous> (C:\Users\小米笔记本\Documents\Arduino\dhtTempTest\serialComms.js:9:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

```
